try:
    print(a)
except:
    print("this is an exception")

#a is not defined so the except function will raise an error